- name: Rust is installed
  command: bash -c 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
  changed_when: false

- name: Install cargo-deb
  command: ~/.cargo/bin/cargo install cargo-deb
  args:
      creates: "~/.cargo/bin/cargo-deb"

- name: Repository is up-tp-date
  become: true
  git:
      repo: 'https://github.com/jwilm/alacritty.git'
      dest: "{{src_dir}}/alacritty"
  notify:
      - Install Alacritty

