- name: Rust is installed
  become: true
  command: bash -c 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
  changed_when: false

- name: Rust is up-to-date
  become: true
  command: rustup update
  changed_when: false

- name: Use Nightly Builds
  become: true
  command: rustup override set nightly
  args:
      chdir: "{{src_dir}}/alacritty"

- name: Install cargo-deb
  command: ~/.cargo/bin/cargo install --force cargo-deb
  args:
      creates: "~/.cargo/bin/cargo-deb"

- name: Repository is up-tp-date
  become: true
  git:
      repo: 'https://github.com/jwilm/alacritty.git'
      dest: "{{src_dir}}/alacritty"
  notify:
      - Install Alacritty

