---
- name: Install pipsi
  pip:
      extra_args: '--user'
      name: pipsi
      state: latest

- name: Install python-packages
  command: pipsi install {{ "--python " + item.exec if item.exec is defined else "" }} {{ item.name }}
  args:
      creates: "{{ ansible_env.HOME }}/.local/venvs/{{ item.name }}"
  with_items: "{{ python_tools }}"

- name: Create config folder
  file:
      path: "{{ ansible_env.HOME }}/.config"
      state: directory

- name: Install config
  file:
      src: "{{ dotfiles_home }}/config/{{ item.path }}"
      dest: "{{ ansible_env.HOME }}/.config/{{ item.path }}"
      state: link
  with_filetree: "{{ dotfiles_home }}/config"
  when: item.state == 'directory'

