- name: Repository is up-tp-date
  git:
      repo: '{{ dotfiles_repo }}'
      dest: "{{ dotfiles_home}}"
      update: no

- name: create symlinks
  file:
      src: "{{ dotfiles_home }}/{{ item }}"
      dest: "{{ ansible_env.HOME }}/.{{ item }}"
      state: link
  with_items:
      - inputrc
      - bashrc
      - tmux.conf
      - tmux
      - wgetrc
