- name: Password-Store is cloned
  become: true
  git:
      repo: https://git.zx2c4.com/password-store
      dest: "{{src_dir}}/password-store"
  notify: Install Password-Store

- name: pass-otp extension is cloned
  become: true
  git:
      repo: https://github.com/tadfisher/pass-otp
      dest: "{{src_dir}}/pass-otp"
  notify: Install pass-otp
